version: 2.0

jobs:
  A:
    docker:
      - image: circleci/ruby:2.4-node
    steps:
      - run: sleep 10

  B:
    docker:
      - image: circleci/ruby:2.4-node
    steps:
      - run: sleep 20

  C:
    docker:
      - image: circleci/ruby:2.4-node
    steps:
      - run: echo "done"

  D:
    docker:
      - image: circleci/ruby:2.4-node
    steps:
      - run: echo "done"

  E:
    docker:
      - image: circleci/ruby:2.4-node
    steps:
      - run: echo "done"
       
  F:
    docker:
      - image: circleci/ruby:2.4-node
    steps:
      - run: echo "done"
  G:
    docker:
      - image: circleci/ruby:2.4-node
    steps:
      - run: echo "done"
  H:
    docker:
      - image: circleci/ruby:2.4-node
    steps:
      - run: echo "done"
  I:
    docker:
      - image: circleci/ruby:2.4-node
    steps:
      - run: echo "done"
      
workflows:
  version: 2
  Test:
    jobs:
      - A
      - B
      - C:
          requires:
            - A
            - B
      - D:
          requires:
            - C
      - E:
          requires:
            - D
            - A
      - F:
          requires:
            - D
            - B
            - H
      - G:
          requires:
            - B
      - H
      - I
          requires:
            - B
