version: 2.0

jobs:
  A:
    docker:
      - image: circleci/ruby:2.4-node
    steps:
      - echo "done"

  B:
    docker:
      - image: circleci/ruby:2.4-node
    steps:
      - echo "done"

  C:
    docker:
      - image: circleci/ruby:2.4-node
    steps:
      - echo "done"

  D:
    docker:
      - image: circleci/ruby:2.4-node
    steps:
      - echo "done"

  E:
    docker:
      - image: circleci/ruby:2.4-node
    steps:
      - echo "done"
      
workflows:
  version: 2
  Test:
    jobs:
      - A
      - B
      - C:
          requires:
            - A
            - B
      - D:
          requires:
            - C
      - D:
          requires:
            - A
            - C
